// questions_os_ch2.js
// Chapter 2: Operating-System Structures
// Stage 1 (Q1–50):   OS Services, UI (CLI/GUI), System Calls
// Stage 2 (Q51–100): Types of System Calls, System Programs, OS Design & Implementation
// Stage 3 (Q101–150): OS Structure (Layered/Microkernel/Modules/Hybrid), Debugging, Boot

const OS_CH2_QUESTIONS = [

  // ══ STAGE 1 — OS SERVICES, UI, SYSTEM CALLS ═══════════════════════════

  // ── OS Services ───────────────────────────────────────────────────────
  {t:"OS Services", q:"What is the primary purpose of operating system services?",
   o:["To manufacture hardware","To provide an environment for program execution and services to users","To replace application programs","To store user data permanently"],
   a:1, e:"OS services provide an environment for execution of programs and services to programs and users."},
  {t:"OS Services", q:"Which OS service allows programs to be loaded into memory and run?",
   o:["I/O operations","File-system manipulation","Program execution","Communications"],
   a:2, e:"Program execution is the OS service that loads a program into memory and runs it, ending either normally or abnormally."},
  {t:"OS Services", q:"What are the three types of user interfaces an OS can provide?",
   o:["CLI, API, and GUI","CLI, GUI, and Batch","Shell, GUI, and Touchscreen","Kernel, Shell, and Desktop"],
   a:1, e:"The three UI types are Command-Line Interface (CLI), Graphical User Interface (GUI), and Batch."},
  {t:"OS Services", q:"Which OS service handles reading and writing files, creating/deleting directories, and permission management?",
   o:["Communications","File-system manipulation","I/O operations","Accounting"],
   a:1, e:"File-system manipulation covers reading/writing files and directories, creating/deleting them, searching, listing, and permission management."},
  {t:"OS Services", q:"How can processes exchange information according to OS communications services?",
   o:["Only via direct hardware access","Via shared memory or message passing","Only through files","Only through the kernel directly"],
   a:1, e:"Communications may be via shared memory or through message passing — packets moved by the OS — on the same machine or over a network."},
  {t:"OS Services", q:"What does the error detection service of an OS do?",
   o:["Prevents all errors from occurring","Takes appropriate action for each type of error to ensure consistent computing","Logs errors but takes no action","Shuts down the system on any error"],
   a:1, e:"For each type of error in CPU, memory, I/O devices, or user programs, the OS should take the appropriate action to ensure correct and consistent computing."},
  {t:"OS Services", q:"Which OS service keeps track of which users use how much and what kinds of resources?",
   o:["Protection","Accounting","Resource allocation","Error detection"],
   a:1, e:"Accounting keeps track of which users use how much and what kinds of computer resources."},
  {t:"OS Services", q:"Resource allocation is needed when:",
   o:["Only one user is logged in","Multiple users or jobs run concurrently","The system is idle","A single process runs"],
   a:1, e:"When multiple users or multiple jobs are running concurrently, resources must be allocated to each of them."},
  {t:"OS Services", q:"Protection ensures that:",
   o:["All hardware is functioning correctly","All access to system resources is controlled","No user can log in remotely","Processes share memory freely"],
   a:1, e:"Protection involves ensuring that all access to system resources is controlled so concurrent processes don't interfere with each other."},
  {t:"OS Services", q:"Security of the system from outsiders requires:",
   o:["Disabling all network connections","User authentication and defending external I/O devices from invalid access","Removing all application programs","Switching to batch mode only"],
   a:1, e:"Security requires user authentication and extends to defending external I/O devices from invalid access attempts."},

  // ── CLI ───────────────────────────────────────────────────────────────
  {t:"CLI", q:"What does CLI stand for?",
   o:["Core Linux Interface","Command-Line Interface","Compiled Language Interpreter","Central Logic Input"],
   a:1, e:"CLI stands for Command-Line Interface — it allows direct command entry by the user."},
  {t:"CLI", q:"Another name for a CLI program is:",
   o:["Kernel module","Command interpreter or shell","GUI manager","System daemon"],
   a:1, e:"A CLI is also called a command interpreter or shell — it fetches a command from the user and executes it."},
  {t:"CLI", q:"Where can a CLI/command interpreter be implemented?",
   o:["Only in the kernel","Only as a system program","In the kernel or as a system program (shell)","Only in application software"],
   a:2, e:"CLIs are sometimes implemented in the kernel, and sometimes as a system program. Multiple 'shell' flavors can be implemented."},
  {t:"CLI", q:"If CLI commands are 'just names of programs', what advantage does this give?",
   o:["Commands run faster","New features can be added without modifying the shell","The shell becomes more secure","Commands require less memory"],
   a:1, e:"If commands are just names of programs, adding new features doesn't require modifying the shell itself — you just add new programs."},
  {t:"CLI", q:"What does a shell primarily do?",
   o:["Manages hardware interrupts","Fetches a command from the user and executes it","Allocates memory to processes","Provides GUI elements"],
   a:1, e:"A shell primarily fetches a command from the user and executes it."},

  // ── GUI ───────────────────────────────────────────────────────────────
  {t:"GUI", q:"Where was the GUI (graphical user interface) invented?",
   o:["MIT","Bell Labs","Xerox PARC","IBM Research"],
   a:2, e:"The GUI was invented at Xerox PARC. It uses a desktop metaphor with icons, mouse, keyboard, and monitor."},
  {t:"GUI", q:"What does the GUI 'desktop metaphor' rely on?",
   o:["Command prompts only","Icons, mouse, keyboard, and monitor with folders and files","Voice commands exclusively","Hardware switches and LEDs"],
   a:1, e:"The GUI uses a desktop metaphor with icons representing files, programs, and actions, controlled via mouse, keyboard, and monitor."},
  {t:"GUI", q:"Microsoft Windows provides which type of interface?",
   o:["CLI only","GUI with a CLI 'command' shell","Touchscreen only","Batch processing only"],
   a:1, e:"Microsoft Windows is primarily a GUI with a CLI 'command' shell available as well."},
  {t:"GUI", q:"Apple Mac OS X's GUI is called:",
   o:["Finder","Aqua","Cocoa","Darwin"],
   a:1, e:"Apple Mac OS X uses the 'Aqua' GUI interface with a UNIX kernel underneath and shells available."},
  {t:"GUI", q:"Touchscreen interfaces replaced mouse-based interaction with:",
   o:["Keyboard shortcuts","Gesture-based actions and virtual keyboards","Voice-only commands","Physical buttons only"],
   a:1, e:"Touchscreen devices use gesture-based actions, virtual keyboards for text entry, and voice commands instead of a mouse."},

  // ── System Calls ──────────────────────────────────────────────────────
  {t:"System Calls", q:"What is a system call?",
   o:["A phone call to technical support","A programming interface to the services provided by the OS","A hardware interrupt","A user login request"],
   a:1, e:"A system call is the programming interface to the services provided by the OS, typically written in a high-level language like C or C++."},
  {t:"System Calls", q:"Programs typically access system calls through:",
   o:["Direct assembly instructions","A high-level Application Programming Interface (API)","Hardware registers only","The GUI desktop"],
   a:1, e:"Programs mostly access system calls via a high-level API rather than making direct system calls."},
  {t:"System Calls", q:"Which of the following is NOT one of the three most common APIs?",
   o:["Win32 API for Windows","POSIX API for UNIX/Linux/Mac","Java API for the JVM","DirectX API for graphics"],
   a:3, e:"The three most common APIs are Win32 (Windows), POSIX (UNIX/Linux/Mac OS X), and Java API (JVM). DirectX is not one of them."},
  {t:"System Calls", q:"What does the system-call interface maintain?",
   o:["A list of user passwords","A table indexed by system call numbers","A log of all user actions","A queue of pending I/O requests"],
   a:1, e:"The system-call interface maintains a table indexed according to system call numbers, invoking the intended system call in the OS kernel."},
  {t:"System Calls", q:"What does the 'run-time support library' do regarding system calls?",
   o:["Compiles OS source code","Hides most OS interface details from the programmer","Manages network connections","Provides GUI rendering"],
   a:1, e:"The run-time support library (built into compiler libraries) manages and hides most details of the OS interface from the programmer."},
  {t:"System Calls", q:"The simplest method of passing parameters to the OS in a system call is:",
   o:["Storing them in a file","Passing them in registers","Using message queues","Writing to a shared buffer"],
   a:1, e:"The simplest method is to pass parameters directly in registers, though this is limited by the number of registers."},
  {t:"System Calls", q:"When there are more parameters than registers, how does Linux/Solaris pass them?",
   o:["By creating a new process","By storing them in a block/table in memory and passing the address in a register","By writing them to disk first","By queuing them in the kernel"],
   a:1, e:"Linux and Solaris store parameters in a block or table in memory, and pass the address of that block as a parameter in a register."},
  {t:"System Calls", q:"The stack method of parameter passing works by:",
   o:["Writing parameters to ROM","The program pushing parameters onto the stack, OS popping them off","Storing parameters in CPU cache","Using direct memory access"],
   a:1, e:"Parameters are pushed onto the stack by the program and then popped off the stack by the operating system."},
  {t:"System Calls", q:"Which parameter-passing methods do NOT limit the number or length of parameters?",
   o:["Register method only","Block/table and stack methods","Stack method only","None — all methods have limits"],
   a:1, e:"Block and stack methods do not limit the number or length of parameters being passed, unlike the register method."},
  {t:"System Calls", q:"The caller of a system call needs to know:",
   o:["The exact memory address of the system call","The kernel source code","Only the API and what the OS will do as a result","The assembly implementation details"],
   a:2, e:"The caller only needs to obey the API and understand what the OS will do as a result — implementation details are hidden."},

  // ══ STAGE 2 — TYPES OF SYSTEM CALLS, SYSTEM PROGRAMS, DESIGN ═════════

  // ── Types of System Calls ─────────────────────────────────────────────
  {t:"System Call Types", q:"Which category of system calls includes create process, terminate process, and load/execute?",
   o:["File management","Device management","Process control","Information maintenance"],
   a:2, e:"Process control system calls include: create/terminate process, end/abort, load/execute, get/set process attributes, wait for time/event, signal event, allocate/free memory."},
  {t:"System Call Types", q:"'Dump memory if error' and 'single step execution' are part of which system call category?",
   o:["Communications","Information maintenance","Process control","Protection"],
   a:2, e:"These are part of Process control — dump memory (for debugging errors) and single step execution (for debugger support) fall in this category."},
  {t:"System Call Types", q:"File management system calls include:",
   o:["Create/delete process","Request/release device","Create/delete file, open/close, read/write/reposition","Get time and date"],
   a:2, e:"File management system calls include: create file, delete file, open, close file, read, write, reposition, get and set file attributes."},
  {t:"System Call Types", q:"'Logically attach or detach devices' belongs to which system call type?",
   o:["File management","Device management","Communications","Protection"],
   a:1, e:"Device management system calls include: request/release device, read/write/reposition, get/set device attributes, and logically attach or detach devices."},
  {t:"System Call Types", q:"Getting/setting time, date, and system data are part of which system call category?",
   o:["Process control","Device management","Information maintenance","Communications"],
   a:2, e:"Information maintenance system calls: get/set time or date, get/set system data, get and set process, file, or device attributes."},
  {t:"System Call Types", q:"In a message-passing communications model, messages go from:",
   o:["Kernel to hardware","Client to server","Device to file","User to register"],
   a:1, e:"In the message passing model, communication goes from client to server using send/receive messages by host name or process name."},
  {t:"System Call Types", q:"Shared-memory communications system calls include:",
   o:["Terminate process","Create and gain access to memory regions","Set file permissions","Request a device"],
   a:1, e:"Shared-memory model system calls include: create and gain access to memory regions, transfer status information, attach and detach remote devices."},
  {t:"System Call Types", q:"Protection system calls are used to:",
   o:["Compress files","Control access to resources, get/set permissions, allow/deny user access","Schedule CPU time","Boot the system"],
   a:1, e:"Protection system calls: control access to resources, get and set permissions, allow and deny user access."},
  {t:"System Call Types", q:"Locks in process control system calls are used for:",
   o:["Physical locks on server rooms","Managing access to shared data between processes","Encrypting files","Booting the OS"],
   a:1, e:"Locks in process control system calls are for managing access to shared data between processes."},
  {t:"System Call Types", q:"In FreeBSD, after a shell executes fork(), it then:",
   o:["Terminates immediately","Calls exec() to load the program into the new process","Requests a device","Logs the event to disk"],
   a:1, e:"In FreeBSD, the shell executes fork() to create a process, then exec() to load the program into that process."},

  // ── System Programs ───────────────────────────────────────────────────
  {t:"System Programs", q:"What do system programs primarily provide?",
   o:["Direct hardware control","A convenient environment for program development and execution","User authentication only","Network packet routing"],
   a:1, e:"System programs provide a convenient environment for program development and execution — some are just interfaces to system calls, others are more complex."},
  {t:"System Programs", q:"Which system program category handles creating, deleting, copying, renaming, and listing files?",
   o:["Status information","Programming-language support","File management","Communications"],
   a:2, e:"File management system programs create, delete, copy, rename, print, dump, list, and generally manipulate files and directories."},
  {t:"System Programs", q:"A 'registry' in status information system programs is used to:",
   o:["Track user login times","Store and retrieve configuration information","Manage network connections","Compile programs"],
   a:1, e:"Some systems implement a registry — used to store and retrieve configuration information."},
  {t:"System Programs", q:"Compilers, assemblers, debuggers, and interpreters belong to which system program category?",
   o:["Background services","File management","Communications","Programming-language support"],
   a:3, e:"Programming-language support system programs include compilers, assemblers, debuggers, and interpreters."},
  {t:"System Programs", q:"What are background services also known as?",
   o:["Application programs","Services, subsystems, or daemons","Shells or CLIs","Kernel modules"],
   a:1, e:"Background services that launch at boot and run until shutdown are known as services, subsystems, or daemons."},
  {t:"System Programs", q:"Background services run in:",
   o:["Kernel context","Hardware context","User context","Network context"],
   a:2, e:"Background services run in user context, not kernel context."},
  {t:"System Programs", q:"What is true about application programs?",
   o:["They are part of the OS kernel","They are not typically considered part of the OS","They always run in kernel mode","They are the same as system programs"],
   a:1, e:"Application programs don't pertain to the system, are run by users, and are not typically considered part of the OS."},
  {t:"System Programs", q:"Most users' view of the OS is defined by:",
   o:["The kernel internals","System programs, not the actual system calls","The hardware specifications","The bootloader"],
   a:1, e:"Most users' view of the operating system is defined by system programs, not the actual system calls."},
  {t:"System Programs", q:"Program loading and execution system programs include:",
   o:["Text editors and compilers","Absolute loaders, relocatable loaders, linkage editors, overlay-loaders","Web browsers and email clients","Disk checking and process scheduling"],
   a:1, e:"Program loading and execution includes absolute loaders, relocatable loaders, linkage editors, overlay-loaders, and debugging systems."},
  {t:"System Programs", q:"Communications system programs allow users to:",
   o:["Compile programs","Send messages, browse web, send email, login remotely, transfer files","Schedule background tasks","Partition the hard drive"],
   a:1, e:"Communications programs allow users to send messages, browse web pages, send email, log in remotely, and transfer files between machines."},

  // ── OS Design & Implementation ────────────────────────────────────────
  {t:"OS Design", q:"When starting to design an OS, what should you define first?",
   o:["The programming language","Goals and specifications","The number of users","The hardware budget"],
   a:1, e:"OS design starts by defining goals and specifications, which are affected by the choice of hardware and type of system."},
  {t:"OS Design", q:"What are 'user goals' in OS design?",
   o:["The OS should maximize resource use","The OS should be convenient, easy to learn, reliable, safe, and fast","The OS should be easy to maintain only","The OS should minimize user interaction"],
   a:1, e:"User goals: the OS should be convenient to use, easy to learn, reliable, safe, and fast."},
  {t:"OS Design", q:"What are 'system goals' in OS design?",
   o:["The OS should be entertaining","Easy to design, implement, maintain; flexible, reliable, error-free, and efficient","Always prioritize speed over reliability","Minimize the number of features"],
   a:1, e:"System goals: the OS should be easy to design, implement, and maintain, as well as flexible, reliable, error-free, and efficient."},
  {t:"OS Design", q:"What is the important principle of separating Policy from Mechanism?",
   o:["Policy = How to do it; Mechanism = What will be done","Policy = What will be done; Mechanism = How to do it","Both are the same thing","Policy applies to hardware; Mechanism to software"],
   a:1, e:"Policy decides WHAT will be done; Mechanism determines HOW to do it. Separating them allows maximum flexibility when policies change."},
  {t:"OS Design", q:"Early operating systems were written in:",
   o:["C and C++","Python and Java","Assembly language","BASIC"],
   a:2, e:"Early OSes were written in assembly language. Then system programming languages like Algol and PL/1, and now mostly C/C++."},
  {t:"OS Design", q:"What is the main advantage of using a high-level language to implement an OS?",
   o:["It runs faster","It is easier to port to other hardware","It uses less memory","It requires less testing"],
   a:1, e:"Using a more high-level language makes the OS easier to port to other hardware, though it may be slightly slower."},
  {t:"OS Design", q:"Modern OS implementations typically use a mix of languages. The lowest levels use:",
   o:["Python","JavaScript","Assembly language","Java"],
   a:2, e:"Modern OSes typically use a mix: lowest levels in assembly, main body in C, system programs in C/C++ or scripting languages."},
  {t:"OS Design", q:"What does emulation allow?",
   o:["An OS to run faster","An OS to run on non-native hardware","A program to bypass system calls","A GUI to run without a display"],
   a:1, e:"Emulation allows an OS to run on non-native hardware by simulating the target architecture."},
  {t:"OS Design", q:"Specifying and designing an OS is best described as:",
   o:["A purely mechanical process","A highly creative task of software engineering","A hardware problem","A simple algorithmic task"],
   a:1, e:"Specifying and designing an OS is a highly creative task of software engineering — there is no single correct solution."},
  {t:"OS Design", q:"The separation of policy and mechanism is important because:",
   o:["It makes the OS run faster","It allows maximum flexibility if policy decisions are to be changed later","It reduces the number of system calls","It simplifies hardware design"],
   a:1, e:"Separating policy from mechanism allows maximum flexibility — if policies change, mechanisms don't need to be rewritten (e.g., the timer mechanism supports various scheduling policies)."},

  // ══ STAGE 3 — OS STRUCTURE, DEBUGGING, GENERATION, BOOT ══════════════

  // ── OS Structure ──────────────────────────────────────────────────────
  {t:"OS Structure", q:"MS-DOS is an example of which OS structure?",
   o:["Layered structure","Microkernel","Simple structure","Modular structure"],
   a:2, e:"MS-DOS is an example of simple structure — written to provide the most functionality in the least space, not divided into modules."},
  {t:"OS Structure", q:"What is the main weakness of MS-DOS's simple structure?",
   o:["Too many layers","Interfaces and levels of functionality are not well separated","It uses too much memory","It cannot run multiple programs"],
   a:1, e:"Although MS-DOS has some structure, its interfaces and levels of functionality are not well separated, creating a fragile design."},
  {t:"OS Structure", q:"The original UNIX OS consists of two separable parts:",
   o:["GUI and CLI","Hardware and firmware","Systems programs and the kernel","Bootloader and device drivers"],
   a:2, e:"UNIX consists of systems programs and the kernel. The kernel is everything below the system-call interface and above the physical hardware."},
  {t:"OS Structure", q:"The UNIX kernel provides:",
   o:["Only the file system","Only CPU scheduling","File system, CPU scheduling, memory management, and other OS functions","Only memory management"],
   a:2, e:"The UNIX kernel provides the file system, CPU scheduling, memory management, and many other OS functions — a large number of functions for one level."},
  {t:"OS Structure", q:"In the Layered Approach, what is Layer 0?",
   o:["The user interface","The kernel API","The hardware","The file system"],
   a:2, e:"In the layered approach, the bottom layer (Layer 0) is the hardware, and the highest layer (Layer N) is the user interface."},
  {t:"OS Structure", q:"In the Layered Approach, each layer uses functions only from:",
   o:["Any layer above or below","Only lower-level layers","Only the layer directly below","Any layer it chooses"],
   a:1, e:"With modularity, layers are selected such that each uses functions and services of only lower-level layers."},
  {t:"OS Structure", q:"What does a Microkernel do?",
   o:["Runs all OS code in user space","Moves as much as possible from the kernel into user space","Combines all OS functions into one large kernel","Eliminates the need for system calls"],
   a:1, e:"A microkernel moves as much from the kernel into user space as possible. Mach is an example; Mac OS X kernel (Darwin) is partly based on it."},
  {t:"OS Structure", q:"How do user modules communicate in a microkernel system?",
   o:["Through shared memory only","Via direct kernel calls","Using message passing","Through hardware interrupts"],
   a:2, e:"Communication takes place between user modules using message passing in a microkernel system."},
  {t:"OS Structure", q:"Which is a BENEFIT of microkernel structure?",
   o:["Faster user-to-kernel communication","Easier to extend and port, more reliable and secure","Larger kernel footprint","No message passing overhead"],
   a:1, e:"Microkernel benefits: easier to extend, easier to port to new architectures, more reliable (less kernel mode code), more secure."},
  {t:"OS Structure", q:"Which is a DETRIMENT of microkernel structure?",
   o:["Harder to extend","Less secure","Performance overhead of user space to kernel space communication","Larger kernel size"],
   a:2, e:"The main detriment of microkernels is the performance overhead of user space to kernel space communication (message passing)."},
  {t:"OS Structure", q:"Loadable kernel modules use which approach?",
   o:["Structured monolithic","Object-oriented — each core component is separate and loadable as needed","Pure layered","Microkernel only"],
   a:1, e:"Loadable kernel modules use an object-oriented approach — each core component is separate, talks over known interfaces, and is loadable as needed."},
  {t:"OS Structure", q:"How are loadable kernel modules similar to layers?",
   o:["They are identical to layers","They are similar but more flexible — any module can call any other","They are completely different","They only work in user space"],
   a:1, e:"Loadable kernel modules are overall similar to layers but with more flexibility — modules can call each other freely. Linux and Solaris use this approach."},
  {t:"OS Structure", q:"Most modern operating systems are:",
   o:["Pure monolithic","Pure microkernel","Pure layered","Hybrid — combining multiple approaches"],
   a:3, e:"Most modern operating systems are hybrid, combining multiple approaches (monolithic + microkernel + modular) to address performance, security, and usability needs."},
  {t:"OS Structure", q:"Linux and Solaris kernels are best described as:",
   o:["Pure microkernel","Monolithic plus modular for dynamic loading","Pure layered","Pure object-oriented"],
   a:1, e:"Linux and Solaris kernels are in kernel address space (monolithic), plus modular for dynamic loading of functionality."},
  {t:"OS Structure", q:"Apple Mac OS X is described as:",
   o:["Pure monolithic","Pure microkernel","Hybrid — layered, with Aqua GUI, Cocoa, Mach microkernel, BSD Unix, I/O kit, and kernel extensions","A simple structure like MS-DOS"],
   a:2, e:"Mac OS X is a hybrid: layered with Aqua UI, Cocoa programming environment, and a kernel consisting of Mach microkernel, BSD Unix, I/O kit, and dynamically loadable kernel extensions."},

  // ── Mobile OS: iOS & Android ─────────────────────────────────────────
  {t:"Mobile OS", q:"iOS is built on top of:",
   o:["Android","Linux","Mac OS X","Windows CE"],
   a:2, e:"iOS is structured on Mac OS X with added functionality, though it does not run OS X applications natively due to different CPU architecture (ARM vs. Intel)."},
  {t:"Mobile OS", q:"Android was developed by:",
   o:["Apple","Microsoft","Open Handset Alliance (mostly Google)","Samsung"],
   a:2, e:"Android was developed by the Open Handset Alliance, mostly Google. It is open source."},
  {t:"Mobile OS", q:"Android is based on:",
   o:["iOS kernel","Mac OS X kernel","A modified Linux kernel","Windows NT kernel"],
   a:2, e:"Android is based on the Linux kernel but modified to add power management and provide process, memory, and device-driver management."},
  {t:"Mobile OS", q:"Android apps are developed in Java and run on:",
   o:["The Linux kernel directly","The Dalvik virtual machine","The iOS runtime","A Python interpreter"],
   a:1, e:"Android apps are developed in Java plus the Android API. Java class files are compiled to bytecode and then translated to run in the Dalvik VM."},
  {t:"Mobile OS", q:"Which API does iOS use for developing apps?",
   o:["Android API","Win32 API","Cocoa Touch Objective-C API","POSIX API"],
   a:2, e:"iOS uses the Cocoa Touch Objective-C API for developing applications."},

  // ── OS Debugging ──────────────────────────────────────────────────────
  {t:"OS Debugging", q:"What is OS debugging?",
   o:["Adding new features to the OS","Finding and fixing errors (bugs) in the OS","Optimizing network performance only","Writing device drivers"],
   a:1, e:"Debugging is finding and fixing errors, or bugs. OS generates log files, core dump files (app failure), and crash dump files (OS failure)."},
  {t:"OS Debugging", q:"A 'core dump' file contains:",
   o:["Kernel memory after a crash","Memory of the process at the time of application failure","The OS log file","Boot sector data"],
   a:1, e:"Failure of an application can generate a core dump file capturing the memory of the process at the time of failure."},
  {t:"OS Debugging", q:"A 'crash dump' file contains:",
   o:["Application memory","Kernel memory after an OS failure","User account information","File system structure"],
   a:1, e:"An operating system failure can generate a crash dump file containing kernel memory for post-failure analysis."},
  {t:"OS Debugging", q:"Profiling is:",
   o:["Measuring network bandwidth","Periodic sampling of instruction pointer to find statistical trends","Writing user profiles to disk","Logging all system calls"],
   a:1, e:"Profiling is periodic sampling of the instruction pointer to look for statistical trends — useful for performance tuning."},
  {t:"OS Debugging", q:"Kernighan's Law states:",
   o:["Writing code is twice as hard as debugging it","Debugging is twice as hard as writing the code, so if you write it as cleverly as possible you can't debug it","All bugs are trivial to find","Testing replaces debugging"],
   a:1, e:"Kernighan's Law: 'Debugging is twice as hard as writing the code in the first place. If you write it as cleverly as possible, you are by definition not smart enough to debug it.'"},
  {t:"OS Debugging", q:"The DTrace tool is available on:",
   o:["Windows only","Linux only","Solaris, FreeBSD, and Mac OS X","Android and iOS only"],
   a:2, e:"DTrace tool is available in Solaris, FreeBSD, and Mac OS X — it allows live instrumentation on production systems."},
  {t:"OS Debugging", q:"In DTrace, 'probes' fire when:",
   o:["The system boots","Code is executed within a provider, capturing state data","A user logs in","A file is created"],
   a:1, e:"DTrace probes fire when code is executed within a provider, capturing state data and sending it to consumers of those probes."},
  {t:"OS Debugging", q:"Performance tuning improves performance by:",
   o:["Adding more RAM","Removing bottlenecks — the OS provides means to compute/display system behavior measures","Reinstalling the OS","Disabling background services"],
   a:1, e:"Performance tuning improves performance by removing bottlenecks. The OS must provide means of computing and displaying measures of system behavior (e.g., 'top' or Windows Task Manager)."},

  // ── OS Generation & Boot ──────────────────────────────────────────────
  {t:"System Boot", q:"What does the SYSGEN program do?",
   o:["Generates system calls","Obtains information about the specific hardware configuration to build a system-specific kernel","Compiles user applications","Manages device drivers at runtime"],
   a:1, e:"SYSGEN obtains information about the specific hardware configuration of the system and is used to build a system-specific compiled kernel or system-tuned version."},
  {t:"System Boot", q:"When power is initialized on a system, execution starts at:",
   o:["The first sector of the hard disk","A fixed memory location","The last loaded program","A random memory address"],
   a:1, e:"When power is initialized on a system, execution starts at a fixed memory location, where firmware ROM holds the initial boot code."},
  {t:"System Boot", q:"Where is the bootstrap loader stored?",
   o:["On the hard disk only","In RAM","In ROM or EEPROM","In the swap partition"],
   a:2, e:"The small bootstrap loader is stored in ROM or EEPROM — it locates the kernel, loads it into memory, and starts it."},
  {t:"System Boot", q:"What does the bootstrap loader do?",
   o:["Runs user applications","Locates the kernel, loads it into memory, and starts it","Manages I/O devices","Provides the user interface"],
   a:1, e:"The bootstrap loader locates the kernel, loads it into memory, and starts it — sometimes via a two-step process with a boot block."},
  {t:"System Boot", q:"GRUB is a common bootstrap loader. What can it do?",
   o:["Run applications directly","Allow selection of kernel from multiple disks, versions, and kernel options","Only boot one fixed OS","Replace the OS kernel"],
   a:1, e:"GRUB (Grand Unified Bootloader) allows selection of kernel from multiple disks, versions, and kernel options — it is a common bootstrap loader."},

];

// Slice into Chapter 2 stage pools
const OS_CH2_STAGE_POOLS = {
  1: OS_CH2_QUESTIONS.slice(0, 50),   // OS Services, UI, System Calls
  2: OS_CH2_QUESTIONS.slice(50, 100), // Types of System Calls, System Programs, OS Design
  3: OS_CH2_QUESTIONS.slice(100),     // OS Structure, Mobile, Debugging, Boot
};
