// questions_hist.js
// Stage 1 (0-49):   Pre-Colonial Philippines — society, beliefs, culture
// Stage 2 (50-99):  Spanish Colonization — conquest, institutions, revolts
// Stage 3 (100-149):Filipino Resistance — Propaganda Movement, institutional impact

const HIST_QUESTIONS = [

  // ══ STAGE 1 — PRE-COLONIAL PHILIPPINES ══════════════════════════════

  // ── Barangay & Social Structure ────────────────────────────────────
  {t:"Barangay", q:"What was the primary political, economic, and sociocultural institution in the Philippines before Spanish colonization?",
   o:["The pueblo","The barangay","The sultanate","The encomienda"],
   a:1, e:"Before Spanish colonization, the barangay was the primary political, economic, and sociocultural institution in the Philippines."},
  {t:"Barangay", q:"How many families could a barangay be composed of?",
   o:["10–30 families","30–100 families","100–500 families","500–1,000 families"],
   a:1, e:"A barangay could be composed of 30–100 families living in a customarily agreed territory."},
  {t:"Barangay", q:"The word 'barangay' comes from the Austronesian word 'balangay,' which means:",
   o:["A village settlement","A sea-going vessel","A chief's house","A communal land"],
   a:1, e:"The term barangay came from the word balangay, an Austronesian sea-going vessel."},
  {t:"Barangay", q:"How could barangays form alliances with each other?",
   o:["Through military conquest only","Through marriage and blood compact","Through tribute payment","Through trade agreements only"],
   a:1, e:"A barangay could form alliances with other barangays to become powerful and prosperous through marriage and blood compact."},
  {t:"Barangay", q:"The three socioeconomic classes of baranganic society are:",
   o:["Rulers, warriors, farmers","Ruling class, commoners/freemen, slaves","Nobles, priests, merchants","Chiefs, artisans, laborers"],
   a:1, e:"Baranganic society was divided into three classes: the ruling class (nobles), commoners/freemen, and slaves."},
  {t:"Barangay", q:"What is the Tagalog term for the ruling class or nobility?",
   o:["Timawa","Maharlika","Maginoo","Alipin"],
   a:2, e:"The ruling class or nobility were known as maginoo in Tagalog and kadatoan in Visayan."},
  {t:"Barangay", q:"What is the Visayan term for commoners or freemen?",
   o:["Maginoo","Timawa","Maharlika","Oripun"],
   a:1, e:"Commoners or freemen were known as maharlika in Tagalog and timawa in Visayan."},
  {t:"Barangay", q:"Philippine slavery was different from other societies because:",
   o:["Slaves had no rights at all","Slaves were not considered property but became so through debt, raids, or punishment","Slaves were always foreigners","Slavery was inherited only"],
   a:1, e:"The slavery system in the Philippines was different — 'slaves' were not considered property but a person became one through debt bondage, raids and wars, and punishment for a crime."},
  {t:"Barangay", q:"Who was the highest official of the barangay?",
   o:["The babaylan","The bagani","The datu","The maharlika"],
   a:2, e:"The datu was the highest official of the barangay — the most powerful person who governed as primary maker, executor, and adjudicator of laws."},
  {t:"Barangay", q:"The datu must come from the ruling class because:",
   o:["Only nobles could read and write","Wealth, power, and influence were needed to maintain such position","The position was always hereditary","Religion required it"],
   a:1, e:"The datu must be from the ruling class because wealth, power, and influence were needed to maintain such a position."},
  {t:"Barangay", q:"What was the role of the bagani in the barangay?",
   o:["Spiritual leader","Warriors/soldiers of the community","Tax collectors","Trade mediators"],
   a:1, e:"The bagani were the warriors of the community, and the datu served as their leader during raids and wars."},
  {t:"Barangay", q:"Social mobility in baranganic society meant that:",
   o:["No one could ever change their class","Members could transfer to other barangays if against the datu's rule","Only slaves could become nobles","Commoners automatically became nobles after 10 years"],
   a:1, e:"Social mobility was possible — members of the barangay, particularly commoners, could even transfer to other barangays if they were against the rule of the datu."},
  {t:"Barangay", q:"According to Francisco Colin's Labor Evangelica, the first 'barangays' were named after:",
   o:["Their founding datu","The boat in which they came to settle the islands","A religious deity","The island they landed on"],
   a:1, e:"They are called barangays, which is the name of a boat, preserving the name from the boat in which they came to settle these islands."},

  // ── Slavery Laws ──────────────────────────────────────────────────
  {t:"Slavery", q:"According to Miguel de Loarca, what was the FIRST class of slaves in the Visayas?",
   o:["Tomatan","Tumaranpoc","Ayuey (bondman of the master's dwelling)","Alipin"],
   a:2, e:"The first and most thoroughly enslaved class was the ayuey — the bondman who served in the master's own dwelling and worked three days for the master and one for himself."},
  {t:"Slavery", q:"The tumaranpoc class of slaves:",
   o:["Lived in the master's house and worked full-time","Lived in their own houses and worked for master one day out of four","Worked only during banquets","Were freed after one year"],
   a:1, e:"Tumaranpoc slaves lived in their own houses and were obliged to go to work for their master one day out of four, having three days for themselves."},
  {t:"Slavery", q:"The tomatan class of slaves worked for their master:",
   o:["Every day","One day a week","Only when there was a banquet or revel","Three days per week"],
   a:2, e:"Tomatan slaves worked in the house of the master only when there was a banquet or revel."},
  {t:"Slavery", q:"According to Loarca, NO one became a slave in the Visayas for:",
   o:["Theft","Debt","Any crime — crimes were punished by fines, not enslavement","Murder"],
   a:2, e:"No Indian in this country is made a slave or put to death for any crime — for each crime there is an established fine."},
  {t:"Slavery", q:"If a culprit could not pay their fine for a crime, they would:",
   o:["Be executed","Borrow money and pledge themselves as a slave until repaid","Be exiled from the barangay","Lose their land permanently"],
   a:1, e:"If the culprit is unable to pay the fine he will borrow the money, and pledge himself to the man from whom he borrows. As a result he becomes a slave until he shall repay what was lent."},

  // ── Laws & Government ─────────────────────────────────────────────
  {t:"Pre-Colonial Laws", q:"According to Francisco Colin, the laws of early Filipinos consisted wholly of:",
   o:["Written codes from India","Traditions and customs observed with great exactness","Decrees from the datu alone","Religious laws from babaylans"],
   a:1, e:"Their laws and policy consisted wholly of traditions and customs, observed with so great exactness that it was not considered possible to break them in any circumstance."},
  {t:"Pre-Colonial Laws", q:"In civil and criminal cases, who served as judge in a barangay?",
   o:["The babaylan","The chief (datu), with assistance from old men of the barangay","A council of all freemen","The most senior warrior"],
   a:1, e:"For the determination of suits both civil and criminal, there was no other judge than the said chief, with the assistance of some old men of the same barangay."},
  {t:"Pre-Colonial Laws", q:"One of the most respected laws in early Filipino society was:",
   o:["The payment of tribute to the datu","Respect of parents and elders, carried to so great a degree that even the father's name could not pass the lips","Military service","Attendance at religious ceremonies"],
   a:1, e:"One law was the respect of parents and elders, carried to so great a degree that not even the name of one's father could pass the lips, in the same way as the Hebrews regarded the name of God."},
  {t:"Pre-Colonial Laws", q:"The death penalty in early Philippine society was:",
   o:["Commonly used for all serious crimes","Never imposed by process of law, except in rare cases where the murderer and victim were both common men with no gold","Always imposed for murder","Reserved only for traitors"],
   a:1, e:"The penalty of death was never imposed by process of law, except when the murderer and his victim were common men and had no gold to satisfy the murder."},
  {t:"Pre-Colonial Laws", q:"According to Colin, how could a person of low extraction gain the status of dato?",
   o:["Only through noble birth","Through accumulating wealth, showing energy and strength, and sometimes through robbery and tyranny","By being elected by the barangay","Through religious authority"],
   a:1, e:"Even if of low extraction, if he gains some wealth by his industry — through farming, trading, or even robbery and tyranny — he gains authority and takes the name of dato."},

  // ── Marriage Customs ──────────────────────────────────────────────
  {t:"Marriage Customs", q:"The Visayan dowry was called:",
   o:["Panhimuyat","Bigaycaya","Pasoso","Catipados"],
   a:1, e:"The dowry, which is called bigaycaya, was always given by the man, with the parents of the girl determining the sum beforehand."},
  {t:"Marriage Customs", q:"Who paid the dowry in early Filipino marriage customs?",
   o:["The bride's family","The groom","Both families equally","The barangay chief"],
   a:1, e:"The bigaycaya (dowry) was always given by the man; the parents of the girl determined the sum beforehand."},
  {t:"Marriage Customs", q:"Included in the bigaycaya was the panhimuyat, which was:",
   o:["A gift for the babaylan","The sum paid to the mother of the bride for her care and labor in rearing and educating her daughter","A fee for the wedding feast","Land given to the couple"],
   a:1, e:"In the bigaycaya was included the panhimuyat, which was the sum to be paid to the mother of the bride in return for her care and labor in the rearing and education of her daughter."},
  {t:"Marriage Customs", q:"According to Juan Francisco de San Antonio, early Filipino marriages were:",
   o:["Permanent and indissoluble like Christian marriages","Not indissoluble — if consorts returned the dowry, they could separate and marry others","Arranged only by parents with no consent from the couple","Only allowed between people of different barangays"],
   a:1, e:"Their marriages were not indissoluble, as are those of Christians. For if the consorts returned the dowry, one to the other, that was sufficient for repudiation."},
  {t:"Marriage Customs", q:"The general rule for number of wives in early Filipino society was:",
   o:["Each man could have as many wives as he could afford","Each man had one legitimate wife","Men could have exactly three wives","There was no rule"],
   a:1, e:"The general rule was for each man to have one legitimate wife; only chiefs and wealthy men were allowed to have slave concubines."},

  // ── Clothing & Culture ────────────────────────────────────────────
  {t:"Early Culture", q:"According to the Boxer Codex, the Bisayans painted their bodies with:",
   o:["Clay and mud","Elegant tattoos using iron or brass rods heated on fire","Plant dyes","Gold dust"],
   a:1, e:"The Bisayans are accustomed to paint their bodies with some very elegant tattoos. They do this with iron or brass rods, the points of which are heated on a fire."},
  {t:"Early Culture", q:"The ordinary dainty or delicacy throughout the Philippine islands, according to Antonio de Morga, was:",
   o:["Rice wine","Buyo (betel)","Dried fish","Coconut"],
   a:1, e:"The ordinary dainty throughout these islands, and in many kingdoms of the mainland of those regions, is buyo (betel)."},
  {t:"Early Culture", q:"The tugbuk and sakra were:",
   o:["Types of weapons used in battle","A penis pin and penis ring used by men, considered symbolic of women's autonomy","Religious offerings to deities","Musical instruments"],
   a:1, e:"Tugbuk (penis pin) and sakra (penis ring) were used by men in the community — they are highly symbolic representations of the egalitarianism and autonomy of women in Southeast Asian communities."},
  {t:"Early Culture", q:"The Boxer Codex is significant in Philippine historiography because:",
   o:["It was written by a Filipino author","It contains detailed and colored illustrations, setting it apart from other accounts","It was the first book printed in the Philippines","It was written by Jose Rizal"],
   a:1, e:"The detailed and colored illustrations found in this manuscript set the Boxer Codex apart from other contemporary accounts, making it highly important to Philippine historiography."},
  {t:"Early Culture", q:"The cloth Bisayan men wrapped around their waist was called:",
   o:["Pezuelo","Purones","Bahaque","Pasonor"],
   a:2, e:"The men wore a cotton cloth two fathoms long wrapped around the waist and between the legs to cover their private parts. They called this cloth bahaque."},

  // ── Spiritual Beliefs ─────────────────────────────────────────────
  {t:"Spiritual Beliefs", q:"The spiritual life in the barangay was led by a local spiritual leader called:",
   o:["Datu in all regions","Babaylan in Visayas and catalonan in Luzon (Tagalog areas)","Baylana everywhere","Maginoo"],
   a:1, e:"The spiritual life in the barangay was led by the local spiritual leader called babaylan in Visayas and catalonan in Luzon, particularly in Tagalog areas."},
  {t:"Spiritual Beliefs", q:"The position of babaylan was usually obtained by:",
   o:["The datu's daughter","A female, though a male could also serve — but he must act and dress as a female","The eldest person in the barangay","Election by the whole community"],
   a:1, e:"This position was usually obtained by a female, but a male could also serve as one; however, he must act and dress as a female."},
  {t:"Spiritual Beliefs", q:"Visayans called their deities 'diwata' while Tagalogs used the term:",
   o:["Anito","Bathala","Laon","Larauan"],
   a:0, e:"Visayans called their deities diwata while the Tagalogs used the term anito."},
  {t:"Spiritual Beliefs", q:"The highest deity among the Tagalogs was called:",
   o:["Laon","Dian Masalanta","Bathala Mei Capal (God the creator)","Lacapati"],
   a:2, e:"Among their many idols, one called Badhala was especially worshipped. The title signifies 'all powerful' or 'maker of all things.' The Tagalogs called this deity Bathala Mei capal, which means 'God the creator or maker.'"},
  {t:"Spiritual Beliefs", q:"According to Fray Juan de Plasencia, early Filipinos had no:",
   o:["Deities","Burial practices","Temples consecrated to performing sacrifices or the adoration of idols","Spiritual leaders"],
   a:2, e:"In all the villages of the Filipinas Islands, there are no temples consecrated to the performing of sacrifices, the adoration of their idols, or the general practice of idolatry."},
  {t:"Spiritual Beliefs", q:"The Visayan creation myth from the Relacion de Loarca says that the first man and woman came from:",
   o:["The sea","The knot of a reed that burst apart","The sky","Two separate gods"],
   a:1, e:"The creation story tells that the land breeze brought forth a reed, which when it grew broke into two sections — one became a man named Sicalac and one became a woman named Sicavay."},
  {t:"Spiritual Beliefs", q:"Early Filipino sacrifices (baylanas/baylanes) were performed during:",
   o:["Every full moon","Cases of sickness, seed-sowing, or war","Weddings only","Daily morning rituals"],
   a:1, e:"The natives have neither time nor place set apart for the offering of prayers and sacrifices to their gods. It is only in case of sickness, and in times of seed-sowing or of war, that sacrifices are offered."},
  {t:"Spiritual Beliefs", q:"According to Pedro Chirino, early Filipinos set up as the chief and superior deity:",
   o:["The sun","Bathala Mei capal","The crocodile","The morning star Tala"],
   a:1, e:"They set up one deity as the chief and superior of all. This deity the Tagalogs call Bathala Mei capal, which means 'God the creator or maker'; the Bisayans call him Laon."},
  {t:"Spiritual Beliefs", q:"The Manunggul Jar, found in Palawan, is significant because it:",
   o:["Shows evidence of early Filipino writing","Signifies prehistoric indigenous burial practices and belief in the afterlife","Proves early trade with China","Shows the first example of Filipino art"],
   a:1, e:"The Manunggul Jar is one of the most important archaeological artifacts in the Philippines as it signifies not only prehistoric indigenous burial practices but also the belief in a soul and life after death."},
  {t:"Spiritual Beliefs", q:"The Gold Death Mask of Oton was believed to:",
   o:["Show wealth and status of the deceased","Repel evil spirits from entering the body","Honor the sun deity","Mark a warrior's grave"],
   a:1, e:"The gold death mask was believed to repel evil spirits from entering the body. The practice of putting a death mask was adopted from the Chinese."},
  {t:"Spiritual Beliefs", q:"Early Filipinos buried their dead:",
   o:["In communal cemeteries outside the village","In their own houses, keeping bodies and bones in chests","In the mountains","At sea"],
   a:1, e:"They buried their dead in their own houses, and kept their bodies and bones for a long time in chests. They venerated the skulls of the dead as if they were living and present."},
  {t:"Spiritual Beliefs", q:"The Philippines was named after:",
   o:["Ferdinand Magellan","Ruy Lopez de Villalobos, who named it after Prince Philip II of Spain","Miguel Lopez de Legazpi","King Charles V of Spain"],
   a:1, e:"The name Philippines came from the navigator Ruy Lopez de Villalobos when he named the archipelago Las Islas Filipinas in 1542, after the heir of the Spanish throne Prince Phillip II."},

  // ══ STAGE 2 — SPANISH COLONIZATION ══════════════════════════════════

  // ── Age of Exploration & Magellan ─────────────────────────────────
  {t:"Spanish Colonization", q:"What was the primary economic motive driving European exploration in the 15th–16th centuries?",
   o:["Finding new lands to settle","Finding a direct route to the profitable Oriental trade of luxury goods like silk and spices","Spreading Christianity only","Escaping political persecution"],
   a:1, e:"The economic motive of finding a direct access to the profitable Oriental trade of luxury goods such as silk and spices was the primary driver of European exploration."},
  {t:"Spanish Colonization", q:"After the fall of Constantinople in 1453, commercial routes to the East fell under control of:",
   o:["Spain and Portugal","Muslim traders and the Italian city-state of Venice","The British Empire","The Dutch"],
   a:1, e:"After the fall of Constantinople to the Ottoman Turks in 1453, commercial routes to the East fell under the control of Muslim traders who, along with the Italian city-state of Venice, monopolized the supply of Oriental products."},
  {t:"Spanish Colonization", q:"Ferdinand Magellan arrived on Philippine shores on:",
   o:["March 16, 1521","April 27, 1565","May 18, 1571","November 20, 1564"],
   a:0, e:"On March 16, 1521, after almost two years of hardship at sea, Magellan's expedition saw the island of Samar in the eastern part of the country."},
  {t:"Spanish Colonization", q:"Magellan named the newly discovered Philippines:",
   o:["Las Islas Filipinas","Archipelago de San Lazaro","Nueva España","Islas del Poniente"],
   a:1, e:"They named the newly discovered territory Archipelago de San Lazaro because it was the feast day of the saint."},
  {t:"Spanish Colonization", q:"The first recorded mass in Philippine history was held on:",
   o:["The island of Samar","Easter Sunday in a small island called 'Mazaua'","Cebu, on the feast of St. Lazaro","Mactan Island"],
   a:1, e:"On Easter Sunday, the first recorded mass in Philippine history was held in a small island called 'Mazaua.' Scholars debate if this was Limasawa or Butuan."},
  {t:"Spanish Colonization", q:"Who was the chief of Mactan that refused to obey the King of Spain and fought Magellan?",
   o:["Raja Humabon","Zula","Cilapulapu (Lapu-lapu)","Raja Colambu"],
   a:2, e:"Cilapulapu refused to obey the king of Spain. Magellan got embroiled in the conflict between the two chiefs of Mactan, Zula and Lapu-lapu, which eventually led to the Battle of Mactan."},
  {t:"Spanish Colonization", q:"How did Magellan die in the Battle of Mactan?",
   o:["Shot by a cannon","Wounded repeatedly by bamboo spears, iron and bamboo cutlasses by the natives","Drowned while retreating","Killed by a poisoned arrow"],
   a:1, e:"So many natives hurled themselves upon Magellan with iron and bamboo spears and cutlasses until they killed their mirror, their light, their comfort, and their true guide."},
  {t:"Spanish Colonization", q:"The Magellan expedition that completed the first circumnavigation was commanded by whom after Magellan's death?",
   o:["Antonio Pigafetta","Juan Sebastian del Cano","Martin de Goiti","Miguel Lopez de Legazpi"],
   a:1, e:"After Magellan's demise, only the little ship Victoria commanded by Sebastian del Cano was able to return safely, completing the first continuous circumnavigation of the world."},
  {t:"Spanish Colonization", q:"Ruy de Villalobos gave the islands the name Las Phelipinas in honor of:",
   o:["King Philip I","Spanish Crown Prince Philip II","Viceroy of Mexico","Pope Paul III"],
   a:1, e:"One expedition led by Ruy de Villalobos gave the islands the name Las Phelipinas in honor of the Spanish crown prince Philip II."},
  {t:"Spanish Colonization", q:"Miguel Lopez de Legazpi performed the blood compact with chief Sikatuna in:",
   o:["Samar","Cebu","Bohol","Manila"],
   a:2, e:"In the island of Bohol, Legazpi performed the blood compact with chief Sikatuna which signified a friendly relationship."},

  // ── Conquest of Manila & Colonial Institutions ─────────────────────
  {t:"Colonial Institutions", q:"Manila was conquered by Legazpi on:",
   o:["April 27, 1565","May 18, 1571","June 21, 1574","November 20, 1564"],
   a:1, e:"On May 18, 1571, after negotiations with Raja Matanda and Lakandula, the adelantado conquered Manila."},
  {t:"Colonial Institutions", q:"Manila was given its distinguished title 'La insigne y siempre leal ciudad' on:",
   o:["May 18, 1571","June 21, 1574","April 27, 1565","November 20, 1564"],
   a:1, e:"Three years later, on June 21, 1574, Manila was given the title La insigne y siempre leal ciudad ('Distinguished and ever loyal city'). That day started the 300-year Spanish rule."},
  {t:"Colonial Institutions", q:"The reduccion was a Spanish policy to:",
   o:["Reduce the tribute paid by Filipinos","Resettle scattered native communities into organized towns under Christian oversight","Reduce the power of the datu","Limit the encomienda system"],
   a:1, e:"The reduccion was a resettlement policy to collect scattered Filipinos into organized towns using the plaza complex, as a 'civilizing' device to make Filipinos law-abiding citizens of the Spanish crown."},
  {t:"Colonial Institutions", q:"The reduccion plan was presented to the Synod of Manila by:",
   o:["Governor-General Legazpi","Franciscan Fr. Juan de Plasencia","Dominican Fr. Domingo de Salazar","Pedro Chirino, S.J."],
   a:1, e:"A plan was presented by the Franciscan Fr. Juan de Plasencia to the Synod of Manila and this was called the reduccion, approved unanimously by all the religious orders."},
  {t:"Colonial Institutions", q:"The encomienda system was established as soon as Legazpi started colonizing the Philippines in:",
   o:["1521","1571","1565","1582"],
   a:2, e:"As soon as Legazpi started colonizing the Philippines in 1565, the encomienda system was established."},
  {t:"Colonial Institutions", q:"The word encomienda comes from the Spanish encomendar, meaning:",
   o:["To conquer","To entrust","To tax","To settle"],
   a:1, e:"The word encomienda comes from the Spanish encomendar, meaning 'to entrust'; it was a grant from the Spanish crown to a meritorious Spaniard to exercise control over a specific place."},
  {t:"Colonial Institutions", q:"The polo y servicios required Filipino and Chinese mestizo males aged 16 to 60 to give:",
   o:["Annual tribute payment","40-day personal service to community projects (reduced to 15 days in 1884)","Military service for 10 years","Half their harvest to the encomendero"],
   a:1, e:"Polo y servicios referred to drafting laborers who were either Filipino or Chinese male mestizos aged 16 to 60. They were obligated to give a 40-day personal service to community projects. It was only in 1884 that labor was reduced to 15 days."},
  {t:"Colonial Institutions", q:"The tribute payment to the King of Spain was eventually replaced by the:",
   o:["Polo y servicios","Bandala","Cedula personal","Indulto de comercio"],
   a:2, e:"By the nineteenth century, the payment of tribute was replaced by the cedula personal (personal identity paper), equivalent to the present residence tax."},
  {t:"Colonial Institutions", q:"The gobernador-general was the King's sole spokesman and representative in the Philippines. He was also president of the:",
   o:["Consejo de las Indias","Real Audiencia (Supreme Court)","Ayuntamiento","Ministerio de Ultramar"],
   a:1, e:"As Captain-General of the colony, the gobernador-general was commander-in-chief of the army and navy, and president of the Real Audiencia, the island's highest judicial body."},
  {t:"Colonial Institutions", q:"The gobernadorcillo was the highest government position a Filipino could attain. He needed to be:",
   o:["A pure-blood Spaniard","Any Filipino or Chinese mestizo, 25 years old, literate in Spanish, and having served as cabeza de barangay for four years","A member of the nobility only","Appointed by the Archbishop"],
   a:1, e:"Any Filipino or Chinese mestizo, 25 years old, literate in oral or written Spanish, and who had been a cabeza de barangay for four years, could be a gobernadorcillo."},
  {t:"Colonial Institutions", q:"The residencia was a judicial review of an official:",
   o:["Conducted secretly and without warning","Conducted publicly at the end of his term by a juez de residencia","Conducted only by the King himself","Conducted by the Pope"],
   a:1, e:"The residencia was the judicial review of a residenciado (one judged) conducted at the end of his term of office, supervised publicly by a juez de residencia."},
  {t:"Colonial Institutions", q:"The Manila-Acapulco Galleon Trade operated for how many years?",
   o:["100 years","150 years","250 years (1565–1815)","300 years"],
   a:2, e:"Running the only regular fleet service in the huge stretch of the Pacific Ocean for two hundred fifty years was the Acapulco galleon (1565–1815)."},
  {t:"Colonial Institutions", q:"The Manila-Acapulco Galleon Trade benefitted primarily:",
   o:["All Filipinos equally","Only a very small coterie of privileged Spaniards, the governor, and Spanish residents in Manila","Chinese merchants","The Catholic Church"],
   a:1, e:"The galleon trade benefitted only a very small coterie of privileged Spaniards — the Spanish governor, members of the consulado, and Spanish residents in Manila."},
  {t:"Colonial Institutions", q:"The bandala referred to:",
   o:["A type of Spanish ship","The annual enforced sale or requisitioning of goods, particularly rice or coconut oil","A military conscription","A type of tribute paid in gold"],
   a:1, e:"Bandala assumed the meaning of the annual enforced sale or requisitioning of goods, particularly of rice or coconut oil in Tayabas, Pampanga, and the Tagalog regions."},

  // ── Early Filipino Revolts ─────────────────────────────────────────
  {t:"Filipino Revolts", q:"The three main triggers of early Filipino revolts were:",
   o:["High taxes, foreign invasion, and drought","Imposition of the Catholic faith, forced labor (polo), and usurpation of land by religious orders","Mistreatment by the datu, famine, and disease","Spanish cruelty, language barriers, and trade restrictions"],
   a:1, e:"The imposition of the Catholic faith, forced labor or polo, and the usurpation of land by the religious orders triggered off reactions from the Filipinos which came in the form of revolts."},
  {t:"Filipino Revolts", q:"The Bancao Revolt of 1621 was triggered by:",
   o:["Forced labor for galleon construction","Attempts to preserve the old religion by Filipinos, particularly in Bohol and Leyte","Land usurpation by friars","Excessive tribute collection"],
   a:1, e:"Attempts at preserving the old religion by Filipinos inspired the revolts led by Tamblot of Bohol and Bancao of Leyte. Both revolts took place in 1621."},
  {t:"Filipino Revolts", q:"The Sumuroy Revolt of 1649 in Samar was primarily caused by:",
   o:["Religious oppression","Demands of forced labor (polo) for galleon construction in Cavite","Land grabbing by Dominican friars","Excessive tribute"],
   a:1, e:"The demands of forced labor or polo took a toll on the Filipinos and were seen in the revolts led by Sumuroy of Samar in 1649 and Maniago of Pampanga in 1660."},
  {t:"Filipino Revolts", q:"The Sumuroy Revolt spread to:",
   o:["Only Samar","Zamboanga, Northern Mindanao, Cebu, Masbate, Camiguin, Albay, and Camarines","Only the Visayas region","Only Luzon"],
   a:1, e:"The Sumuroy Revolt spread to Zamboanga, Northern Mindanao, Cebu, Masbate, Camiguin, Albay, and Camarines."},
  {t:"Filipino Revolts", q:"The agrarian uprisings of 1745–1746 were caused by:",
   o:["Excessive tribute demands","Religious orders usurping lands from natives in Batangas, Bulacan, Cavite, Laguna, and Rizal","Forced conversion to Christianity","The polo system"],
   a:1, e:"As religious orders usurped lands from the natives, agrarian uprisings became rampant in the provinces of Batangas, Bulacan, Cavite, Laguna, and Rizal in 1745–1746."},
  {t:"Filipino Revolts", q:"In the King of Spain's letter regarding the land usurpation, he said the Indians should settle disputes by:",
   o:["Armed revolt if necessary","Using peaceable means without going to the extreme of employing armed force","Appealing to the Pope","Seeking help from China"],
   a:1, e:"Considering how important it is that the Indians know of the recourse which they can have when they are oppressed, it would be expedient that the government give them information, so that they may use these peaceable means without going to the extreme of employing armed force."},

  // ── Church and State ──────────────────────────────────────────────
  {t:"Church & State", q:"Marcelo del Pilar derisively called the situation in the Philippines:",
   o:["La soberanía colonial","La soberanía monacal (monastic supremacy) or frailocracia (friarocracy)","La república española","El gobierno colonial"],
   a:1, e:"Marcelo H. del Pilar derisively called the situation in the Philippines la soberanía monacal (monastic supremacy) or frailocracia (friarocracy), because the Spanish friars ruled supreme, even over governmental matters."},
  {t:"Church & State", q:"The first open anti-friar demonstration in Manila took place on:",
   o:["July 4, 1896","March 1, 1888","December 30, 1896","November 7, 1751"],
   a:1, e:"Probably the first and only open anti-friar demonstration against the intolerable church abuses took place in Manila on March 1, 1888, led by Doroteo Cortes, aided secretly by Marcelo H. del Pilar and Jose Ramos Ishikawa."},
  {t:"Church & State", q:"The demonstrators' manifesto in the 1888 anti-friar march declared:",
   o:["'Viva Filipinas! Death to Spain!'","'Long Live the Queen! Long Live the Army! Down with the Friars!'","'Give us liberty or give us death!'","'The Philippines for Filipinos!'"],
   a:1, e:"The demonstrators' manifesto declared 'Long Live the Queen! Long Live the Army! Down with the Friars!'"},

  // ══ STAGE 3 — PROPAGANDA MOVEMENT & INSTITUTIONAL IMPACT ═══════════

  // ── Background of the Propaganda Movement ─────────────────────────
  {t:"Propaganda Movement", q:"The Propaganda Movement was essentially a Filipino-led campaign for:",
   o:["Independence from Spain","Reform and assimilation — advocating for equal treatment under Spanish law","Revolution and armed resistance","Separation of Church and State only"],
   a:1, e:"The Propaganda Movement was essentially a Filipino-led campaign for reform and assimilation which can be dated from the appearance of the reformist bilingual newspaper Diariong Tagalog in 1882 to the demise of La Solidaridad in 1895."},
  {t:"Propaganda Movement", q:"The educational reform of 1863 was significant because it:",
   o:["Made education free for all Filipinos","Opened institutions of higher learning in the colony to all who could afford it, allowing rich mestizos and natives to study","Made Spanish the official language","Expelled all foreign friars"],
   a:1, e:"The educational reform of 1863 opened institutions of higher learning in the colony to all who could afford it. This reform gave the rich mestizos and natives the opportunity to send their children to schools and colleges in Manila and Europe."},
  {t:"Propaganda Movement", q:"The wealthy, educated Filipino class that led the Propaganda Movement were called:",
   o:["Ilustrados","Indios","Mestizos","Gobernadorcillos"],
   a:0, e:"The ilustrados (distinguished, educated Filipinos) differentiated themselves from the masses of indios, led the criticism against the colonial government, and proposed political and economic reforms."},
  {t:"Propaganda Movement", q:"The Cavite Mutiny of 1872 destroyed the early reform movement by:",
   o:["Starting a revolution","State repression that implicated prominent Filipinos as conspirators — many were imprisoned, exiled, or executed (including the Gomburza priests)","Convincing Filipinos to abandon reform","Leading directly to the Propaganda Movement immediately"],
   a:1, e:"The movements for liberal reform and secularization would be destroyed by state repression following the Cavite Mutiny of 1872. Prominent Filipinos were implicated as conspirators; many were imprisoned, exiled, or executed — the fate that befell the Gomburza priests."},
  {t:"Propaganda Movement", q:"The secularization issue was a movement demanding:",
   o:["Separation of Church and State","Equality of treatment between Filipino secular priests and Spanish regular clergy, and turnover of local parishes to Filipino priests","Abolition of all religious orders","Complete religious freedom"],
   a:1, e:"Within the Church, there was a movement for change led by Fr. Pedro Pelaez and later Fr. Jose Burgos demanding equality of treatment between Filipino secular priests and Spanish regular clergy, and the turnover of administration of local parishes to Filipino priests."},
  {t:"Propaganda Movement", q:"The Propaganda Movement ultimately proved to be a failure because:",
   o:["The propagandists gave up and returned home","Basic rights like freedom of speech, press, and representation in the Cortes continued to be denied to Filipinos despite tireless efforts","Spain immediately agreed to all demands","The propagandists were all arrested"],
   a:1, e:"In the end, the campaign proved to be a failure as basic rights and privileges such as freedom of speech, the press, and association and representation to the Cortes continued to be denied to the Filipinos."},

  // ── La Solidaridad ─────────────────────────────────────────────────
  {t:"La Solidaridad", q:"La Solidaridad was established in:",
   o:["1872","1880","1889 in Barcelona","1895"],
   a:2, e:"Established in 1889, the bimonthly newspaper La Solidaridad was the official mouthpiece of the Propaganda Movement, the voice of the Filipinos in Spain. It was organized in Barcelona."},
  {t:"La Solidaridad", q:"The first editor of La Solidaridad was:",
   o:["Jose Rizal","Marcelo H. del Pilar","Graciano Lopez Jaena","Mariano Ponce"],
   a:2, e:"La Solidaridad was organized in Barcelona with Graciano Lopez Jaena as its first editor, followed by Marcelo H. del Pilar when the publication moved to Madrid."},
  {t:"La Solidaridad", q:"Copies of La Solidaridad were smuggled into the Philippines through Hong Kong by:",
   o:["Jose Rizal","Marcelo del Pilar","Jose Ma. Basa","Antonio Luna"],
   a:2, e:"Copies of the newspaper were also smuggled to the Philippines through Hong Kong by Jose Ma. Basa."},
  {t:"La Solidaridad", q:"La Solidaridad was forced to close up in 1895 due to:",
   o:["Spanish government censorship","Insufficiency of funds","Lack of readership","The arrest of its editors"],
   a:1, e:"In 1895, the Sol was forced to close up because of insufficiency of funds."},
  {t:"La Solidaridad", q:"Jose Rizal's pen name in La Solidaridad was:",
   o:["Plaridel","Taga-Ilog","Dimasalang or Laong Laan","Tikbalang"],
   a:2, e:"The writers either signed their real names or adopted pen names such as Dimasalang and Laong Laan (Jose Rizal); Plaridel (Marcelo H. del Pilar); Taga-Ilog (Antonio Luna)."},

  // ── Key Propagandists ─────────────────────────────────────────────
  {t:"Key Propagandists", q:"Graciano Lopez Jaena was born in:",
   o:["Calamba, Laguna","Jaro, Iloilo","Bulakan, Bulacan","Manila"],
   a:1, e:"Graciano Lopez Jaena was born on December 29, 1856 in Jaro, Iloilo."},
  {t:"Key Propagandists", q:"Lopez Jaena's early satirical piece that depicted the abuses of the friars was entitled:",
   o:["Noli Me Tangere","El Filibusterismo","Fray Botod","La Solidaridad"],
   a:2, e:"At a very young age, he wrote a satirical piece entitled 'Fray Botod' which depicted the abuses of the friars."},
  {t:"Key Propagandists", q:"Marcelo H. del Pilar's law degree was from:",
   o:["Ateneo de Manila","University of Santo Tomas","University of Barcelona","University of Madrid"],
   a:1, e:"Del Pilar acquired his law degree from the University of Santo Tomas in 1880."},
  {t:"Key Propagandists", q:"Marcelo del Pilar wrote a mock prayer book that criticized the friars, called:",
   o:["Noli Me Tangere","Pasiong Mahal","Dasalan at tocsohan","El Filibusterismo"],
   a:2, e:"Del Pilar wrote Dasalan at tocsohan, a mock prayer book which criticized the friars."},
  {t:"Key Propagandists", q:"Del Pilar was also instrumental in founding which newspaper in 1882?",
   o:["La Solidaridad","Diariong Tagalog (the first bilingual newspaper in Spanish and Tagalog)","El Liberalismo","Kalayaan"],
   a:1, e:"He was also instrumental in the founding of Diariong tagalog in 1882, the first bilingual newspaper in Spanish and Tagalog."},
  {t:"Key Propagandists", q:"Jose Rizal published his first novel Noli Me Tangere in:",
   o:["1885","1887","1889","1891"],
   a:1, e:"He published his first novel, Noli me tángere (Touch Me Not), in 1887. The Noli exposes the social ills afflicting colonial Philippines."},
  {t:"Key Propagandists", q:"In Rizal's essay 'On the Indolence of the Filipinos,' he argued that Filipino 'indolence' was:",
   o:["A natural characteristic of tropical people","An evil fostered and magnified by misgovernment — an effect of misgovernment, not a cause","Caused by the hot climate","Due to lack of education"],
   a:1, e:"Rizal argued that indolence in the Philippines is a magnified indolence, a snow-ball indolence — an evil which increases in direct proportion to the square periods of time, an effect of misgovernment and backwardness, not a cause of them."},
  {t:"Key Propagandists", q:"Jose Rizal organized La Liga Filipina on:",
   o:["December 30, 1896","July 3, 1892","March 1, 1888","November 20, 1564"],
   a:1, e:"He organized a society exclusively for Filipinos, La Liga Filipina (The Filipino League), on July 3, 1892. After three days of the society's establishment, he was arrested and exiled to Dapitan."},
  {t:"Key Propagandists", q:"Jose Rizal was executed on:",
   o:["July 3, 1892","December 30, 1896 in Bagumbayan, Manila","March 1, 1888","January 20, 1896"],
   a:1, e:"Rizal was tried in court and pronounced guilty of treason and sedition. Rizal was executed on December 30, 1896 in Bagumbayan, Manila."},
  {t:"Key Propagandists", q:"According to Lopez Jaena in 'The Philippines in Distress,' the most notable cause of the backwardness of the Philippines was:",
   o:["The tropical climate","The character of the Filipinos","The normalous education given to youth in schools — they learn to pray but never to work","The lack of natural resources"],
   a:2, e:"After those mentioned in the preceding article, the most notable cause of the backwardness of the Philippines is the normalous education given to the youth in schools. They learn to read correctly and to write gracefully, but they do not learn useful things because they are not taught any. They are taught how to pray but never to work."},

  // ── Institutional Impact ───────────────────────────────────────────
  {t:"Institutional Impact", q:"According to Lopez Jaena, the supreme remedies to reactivate Philippine commerce were:",
   o:["Military force and tribute","Abolition of differential duties, freedom of commerce, freedom of association, freedom of the press, and establishment of free ports","Expulsion of all Spaniards","Total independence from Spain"],
   a:1, e:"The abolition of the existing differential duties, freedom of commerce, freedom of association, freedom of the press, freedom to establish free ports, are the supreme remedies to reactivate and restore to life the already comatose Philippine commerce."},
  {t:"Institutional Impact", q:"Del Pilar argued in Monastic Supremacy that the friars maintained their power by:",
   o:["Military force alone","Fanning resentment between the people and the government, and preserving diversity of languages to impede popular education","Bribing the Governor-General","Controlling the army"],
   a:1, e:"To achieve this, they count on the diversity of languages among the rulers and the ruled; and to preserve that diversity to impede popular education, and to avoid at any cost that the people and the government come to understand each other."},
  {t:"Institutional Impact", q:"The Educational Decree of 1863 established:",
   o:["Universities for Spaniards only","A free compulsory publicly-supported system of primary schools, with each town having at least two schools","A single national university in Manila","Schools exclusively for Filipino elites"],
   a:1, e:"A free compulsory publicly-supported system of primary schools came with the Educational Decree of 1863, simultaneous with the establishment of a men's normal school to prepare future schoolmasters. Each town had at least two schools, one for boys and another for girls."},
  {t:"Institutional Impact", q:"The University of Santo Tomas was originally called:",
   o:["Colegio de Niños","Colegio Maximo de San Ignacio","Colegio de Nuestra Señora del Santísimo Rosario","College of San Jose"],
   a:2, e:"The present University of Santo Tomas, established in 1611, was originally called Colegio de Nuestra Señora del Santísimo Rosario. It was converted to a Dominican University in 1645."},
  {t:"Institutional Impact", q:"The Philippine Revolution of 1896 centered in the areas where:",
   o:["The ilustrados lived","The vast friar haciendas thrived: Cavite, Laguna, Bulacan, Morong, and Manila province","The strongest datu class existed","Spanish garrisons were located"],
   a:1, e:"It was not surprising that the Philippine Revolution centered in the areas where the vast haciendas (friar estates) thrived: Cavite, Laguna, Bulacan, Morong, and Manila province."},
  {t:"Institutional Impact", q:"The separation of Church and State became one of the outstanding innovations of the:",
   o:["Propaganda Movement itself","Malolos Constitution in 1898","Philippine Revolution of 1896","Educational Decree of 1863"],
   a:1, e:"The separation of Church and State became one of the outstanding innovations of the Malolos Constitution in 1898."},
  {t:"Institutional Impact", q:"Rizal concluded in 'On the Indolence of the Filipinos' that without _______, no reform is possible:",
   o:["Armed revolution","Education and liberty — the soil and the sun of mankind","Money and resources","Spanish cooperation"],
   a:1, e:"Without education and liberty — the soil and the sun of mankind — no reform is possible, no measure can give the desired result."},
  {t:"Institutional Impact", q:"The Propaganda Movement, while failing in its immediate aims, succeeded in:",
   o:["Gaining Philippine independence","Igniting a sense of national identity and unity among Filipinos in Spain that sparked the revolution","Ending friar power","Achieving representation in the Spanish Cortes"],
   a:1, e:"All things considered, however, the movement did succeed in igniting a sense of national identity and unity among Filipinos in Spain that would soon reach the motherland and spark the revolution."},
  {t:"Institutional Impact", q:"One-fourth of the total area of friar estates in the Philippines was located in:",
   o:["Manila","Laguna","Cavite","Bulacan"],
   a:2, e:"One-fourth of the total area of friar estates in the Philippines was located in Cavite, and 48% of the total arable lands in the Tagalog provinces belonged to the friars."},
  {t:"Institutional Impact", q:"The Puente Colgante (now Quezon Bridge), the first suspension bridge in the Far East, was designed by:",
   o:["Antonio Pigafetta","Legazpi himself","Gustave Eiffel of the famous tower in Paris","A Filipino engineer"],
   a:2, e:"The Puente Colgante (now Quezon Bridge), the first suspension bridge in the Far East, was designed by Gustave Eiffel of the famous tower in Paris. It measured 110 meters long and seven meters wide."},
  {t:"Institutional Impact", q:"The Royal Economic Society of Friends of the Country (Real Sociedad Económica de Amigos del País) was organized in:",
   o:["1565","1712","1780","1863"],
   a:2, e:"Following the royal order 'to form a society of learned and competent persons capable of producing useful ideas,' Governor Jose de Basco y Vargas formally organized, in 1780, the Real Sociedad Económica de Amigos del País."},
  {t:"Institutional Impact", q:"The positive results of the Manila-Acapulco Galleon Trade included intercultural exchanges — which Filipino product came to Mexico through the trade?",
   o:["Rice","The carabao (known by 1737 in Mexico), mango, tamarind, and tuba-making","Corn","Gold"],
   a:1, e:"Among the positive results of the galleon trade were intercultural exchanges: the carabao (known by 1737 in Mexico), mango of Manila, tamarind and rice, cockfighting, and the famous manton de Manila came to Mexico through the trans-Pacific trade."},
];

// Slice into stages
const HIST_STAGE_POOLS = {
  1: HIST_QUESTIONS.slice(0, 50),
  2: HIST_QUESTIONS.slice(50, 100),
  3: HIST_QUESTIONS.slice(100),
};
